"""modelo inicial v2

Revision ID: 3592f17ee1ca
Revises: 
Create Date: 2026-06-08 01:50:49.553369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3592f17ee1ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicamento',
    sa.Column('id_medicamento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_comercial', sa.String(length=100), nullable=False),
    sa.Column('nome_generico', sa.String(length=100), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('forma_uso', sa.Enum('unidade', 'ml', name='formausoenum'), nullable=False),
    sa.Column('observacoes', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id_medicamento')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('endereco_rua', sa.String(length=100), nullable=True),
    sa.Column('endereco_numero', sa.Integer(), nullable=True),
    sa.Column('endereco_complemento', sa.String(length=50), nullable=True),
    sa.Column('endereco_bairro', sa.String(length=50), nullable=True),
    sa.Column('endereco_cep', sa.String(length=10), nullable=True),
    sa.Column('endereco_cidade', sa.String(length=50), nullable=True),
    sa.Column('endereco_estado', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('usuario_medicamento',
    sa.Column('id_tratamento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_medicamento', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('duracao_dias', sa.Integer(), nullable=False),
    sa.Column('intervalo_horas', sa.Integer(), nullable=False),
    sa.Column('dosagem', sa.String(length=50), nullable=False),
    sa.Column('observacoes', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['id_medicamento'], ['medicamento.id_medicamento'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_tratamento')
    )
    op.create_table('alerta',
    sa.Column('id_alerta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_tratamento', sa.Integer(), nullable=False),
    sa.Column('data_horario_alerta', sa.DateTime(), nullable=False),
    sa.Column('status_alerta', sa.Enum('pendente', 'consumido', 'nao_consumido', name='statusalertaenum'), nullable=False),
    sa.ForeignKeyConstraint(['id_tratamento'], ['usuario_medicamento.id_tratamento'], ),
    sa.PrimaryKeyConstraint('id_alerta')
    )
    op.create_table('registro_uso',
    sa.Column('id_registro', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_alerta', sa.Integer(), nullable=False),
    sa.Column('data_horario_consumo', sa.DateTime(), nullable=False),
    sa.Column('observacoes', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['id_alerta'], ['alerta.id_alerta'], ),
    sa.PrimaryKeyConstraint('id_registro')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registro_uso')
    op.drop_table('alerta')
    op.drop_table('usuario_medicamento')
    op.drop_table('usuario')
    op.drop_table('medicamento')
    # ### end Alembic commands ###
